### ISSUE TITLE
Is it necessary to load files' thumbnails asynchronously?

### ISSUE THREAD

**Issue by Poker-sang** [castorix/WinUI3_IFileDialog#1]
I love this repo because this is what has been confusing me.

I noticed that you actually load the thumbnails synchronously (The list will only be displayed after finishing loading). I wonder if there are hundreds or thousands of icons waiting for being loaded, shall we use async? And is it worth keeping the thumbnails in memory for the next display?

Many thanks!

**Comment by castorix** [comment]
I used GetThumbnailAsync because there is no GetThumbnailSync...
But it is slow and another method I had posted in this thread could be better : https://github.com/microsoft/microsoft-ui-xaml/discussions/7943

**Comment by Poker-sang** [comment]
Thanks! I would like to try it out soon.

**Comment by Poker-sang** [comment]
Thanks, it's really much faster with this method, but I'm also having other problems. When I manually PInvoke Shell32.SHGetFileInfo or Shell32.ExtractAssociatedIcon, I get only 32-bit(?) color, whereas when I use GetThumbnailAsync or System.Drawing's Icon.ExtractAssociatedIcon, I get normal 256-bit RGBA color. How to solve this problem?
ICO:
![ICO](https://github.com/castorix/WinUI3_IFileDialog/assets/62325494/da04b1ac-aadd-4dbb-808c-8cc20ff82c0c)
PNG:
![PNG](https://github.com/castorix/WinUI3_IFileDialog/assets/62325494/862c1898-583a-4687-ad51-d510dc22e54c)
